### PR TITLE
Not delete Keypad on user delete

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@jwinzer Should a keypad be deleted, if a user is deleted? If so, I'll close this PR.

### CODE REVIEW

**Comment by jwinzer** [comment]
The keypad should be deleted if the user gets deleted who owns the keypad.

**Comment by FinnStutzenstein** [comment]
Ok.

**Comment by jwinzer** [comment]
Shouldn't it be 
user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
to delete the keypad when user is deleted?

**Comment by FinnStutzenstein** [comment]
I think this is the default. At least the keypad is deleted, if the user is, so currently it works as expected (except the autoupdate, this is another issue, but I have a solution for it).

**Pull request closed without merging**
