### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
If this is ok, I will squash the commits together and merge. These are just stylistic changes.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@jwinzer Please test. The most of the commits are little stuff. The main changes are: two new config options to disable subsystems of the voting plugin. Added the `can_vote` permission. All users who have this permission can vote now.

**Comment by jwinzer** [comment]
I haven't tested the changes. However, I prefer to have these configs:
- voting_enable_principles: This enables voting principle and voting shares
- voting_enable_proxies: This enables proxies and absentee votes

I'm not sure though how well these can be separated.

**Comment by FinnStutzenstein** [comment]
So moving the proxy part to the absentee votes? Ok for me, I'll check this

**Comment by jwinzer** [comment]
Yes, but name should be voting_enable_proxies. Label can be "Enable proxies and absentee votes". The other label can be "Enable voting principles and shares"

**Comment by FinnStutzenstein** [comment]
Done.

**Pull request merged**
